ARG POSTGRES_VERSION=alpine
FROM postgres:${POSTGRES_VERSION}

# Based on laradock/laradock (Maintainer not specified)
LABEL maintainer="Ivan Terentev <terentev.pro@gmail.com>"

CMD ["postgres"]

EXPOSE 5432
